name: API CI
#on: [push, pull_request]

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/playwright.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: /api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Run tests
        shell: bash
        run: npm test
